### ISSUE TITLE
Expo

### ISSUE THREAD

**Issue by NahumG10** [web-ridge/react-native-paper-autocomplete#12]
Does it work with expo? i couldn't run it

**Comment by RichardLindhout** [comment]
It should work now te example uses expo too but you should install react-native-reanimated

**Comment by Angelk90** [comment]
@RichardLindhout : Could you create an example at https://snack.expo.dev to be able to see it?

**Comment by RichardLindhout** [comment]
I think Expo still needs formatJS polyfill on Android since it has no Intl support yet in the Hermes version next release of expo will fix this (probably)

See readme for polyfill instructions

**Comment by RichardLindhout** [comment]
Expo should work fine, we're using it in an expo app no native deps required
