### ISSUE TITLE
When having a selected value, focussing the field which is lower than the top scroll causes the X mark and dropdown items to pop up at the top of the scrollview

### ISSUE THREAD

**Issue by Rubenvdveen** [web-ridge/react-native-paper-autocomplete#2]
When having a selected value once, focussing the field which is lower than the top scroll causes the X mark and dropdown items to pop up at the top of the scrollview.

Image how it's supposed to work:
<img width="603" alt="Screenshot 2021-06-25 at 10 14 13" src="https://user-images.githubusercontent.com/22151095/123393149-193e6280-d59e-11eb-9c39-27b95c2f8c98.png">

Image after selecting a value once and re-focussing:
<img width="597" alt="Screenshot 2021-06-25 at 10 14 54" src="https://user-images.githubusercontent.com/22151095/123393257-31ae7d00-d59e-11eb-88be-2717b0273bf7.png">

**Comment by RichardLindhout** [comment]
Do you have body scroll? You can't have body scroll in React Native Web apps

**Comment by RichardLindhout** [comment]
You should use it inside a 
```jsx
<ScrollView></ScrollView> 
```

**Comment by RichardLindhout** [comment]
Hmm I have the same problem now :-D

**Comment by RichardLindhout** [comment]
Nevermind, it was because expo does allow body scroll by default. You should be fine by something like this in your css
```css
body,html,#root{min-height:100%;height:100%;max-height:100%;overflow:hidden;}
```
And use a ScrollView for the elements

**Comment by RichardLindhout** [comment]
For expo users, wrap your whole app in a custom View

```jsx
export default function App() {
  return (
    <View
      style={
        Platform.OS === 'web' ? { flex: 1, maxHeight: '100vh' } : { flex: 1 }
      }
    >
      <PaperProvider>
        <AppInner />
      </PaperProvider>
    </View>
  );
}
```

**Comment by RichardLindhout** [comment]
Please update to v0.2.0, I think I fixed the issue you are describing by recalculating the position if the user clicks the element

**Comment by Rubenvdveen** [comment]
Thanks for the updates, it seems to work fine using a scrollview and the View wrapped around the App component, but there is one new problem now:

When having the autocomplete focussed, it's impossible to scroll.

Video:
https://youtu.be/0yGnSWfeleM
